#Copyright 2017 Reactive Ops Inc.
#
#Licensed under the Apache License, Version 2.0 (the “License”);
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an “AS IS” BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

version: 2

jobs:
  end-to-end:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/reckoner
    steps:
      - setup_remote_docker
      - run:
          name: Get Binaries
          command: |
            wget https://storage.googleapis.com/kubernetes-release/release/v1.12.7/bin/linux/amd64/kubectl
            chmod 0755 kubectl

            wget https://storage.googleapis.com/kubernetes-helm/helm-v2.13.1-linux-amd64.tar.gz
            tar xzvf helm-* -C /tmp/
            mv /tmp/linux-amd64/helm .

            wget https://github.com/kubernetes-sigs/kind/releases/download/0.2.1/kind-linux-amd64
            mv kind-linux-amd64 kind
            chmod 0755 kind

            ./kind create cluster
            echo "export KUBECONFIG=$(./kind get kubeconfig-path --name=kind)" >> $BASH_ENV
            ./kubectl config current-context
      - run:
          name: Install Helm
          command: |
            count=0
            while ! ./kubectl version || [[ $count -lt 10 ]]; do sleep 3; let "count++"; done
            ./kubectl apply -f \<< EOF
            apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: tiller
              namespace: kube-system
            ---
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: tiller
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: cluster-admin
            subjects:
              - kind: ServiceAccount
                name: tiller
                namespace: kube-system
            EOF
            ./helm init --service-account tiller
            count=0
            while ! helm ls || [[ $count -lt 10 ]]; do sleep 3; let "count++"; done
            helm ls
            pip install --user .
            reckoner --version
  build-2.7:
    docker:
      - image: circleci/python:2.7
    environment: ~
    working_directory: ~/reckoner
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: |
            sudo pip install .
            reckoner --version
            sudo pip install -r tests/requirements.txt
            pytest
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t reckoner .
            docker run --rm reckoner --version
  build-3.6:
    docker:
      - image: circleci/python:3.6
    environment: ~
    working_directory: ~/reckoner
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: |
            sudo pip install .
            reckoner --version
            sudo pip install -r tests/requirements.txt
            pytest
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t reckoner .
            docker run --rm reckoner --version
  build-3.7:
    docker:
      - image: circleci/python:3.7
    environment: ~
    working_directory: ~/reckoner
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: |
            sudo pip install .
            reckoner --version
            sudo pip install -r tests/requirements.txt
            pytest
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t reckoner .
            docker run --rm reckoner --version
            
  release:
    docker:
      - image: circleci/python:3
    environment:
      PYPI_USERNAME: ReactiveOps
      GITHUB_ORGANIZATION: $CIRCLE_PROJECT_USERNAME
      GITHUB_REPOSITORY: $CIRCLE_PROJECT_REPONAME
    working_directory: ~/reckoner
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create release
          command: |
            echo "Using Repo:$GITHUB_REPOSITORY and Org:$GITHUB_ORGANIZATION"
            git fetch --tags
            curl -O https://raw.githubusercontent.com/reactiveops/release.sh/v0.0.2/release
            /bin/bash release
      - run:
          name: package and upload
          command: |
            sudo pip install twine
            python setup.py sdist bdist_wheel
            twine upload dist/*

workflows:
  version: 2
  build:
    jobs:
      - build-2.7:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build-3.6:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build-3.7:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - release:
          requires:
            - build-2.7
            - build-3.6
            - build-3.7
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - end-to-end:
          filters:
            branches:
              only: /end-to-end/
